"""
Canonical provider catalog for Ami.

This is the single source of truth for all supported providers.
Fields are used by the idempotent seed_providers script to create or
update provider rows without touching user subscription data.

logo_path values are frontend public-root paths (e.g. /assets/logos/…)
and must match the files in ami/frontend/public/assets/logos/.
"""
from typing import Optional


# fmt: off
PROVIDER_CATALOG: list[dict] = [
    dict(
        name         = "Adobe Firefly",
        slug         = "adobe-firefly",
        category     = "image",
        website_url  = "https://firefly.adobe.com",
        account_url  = "https://account.adobe.com/",
        billing_url  = "https://account.adobe.com/plans",
        link_notes   = None,
        logo_color   = "#FF0000",
        logo_path    = "/assets/logos/adobe-firefly-color.svg",
        is_active    = True,
    ),
    dict(
        name         = "ChatGPT",
        slug         = "chatgpt",
        category     = "chat",
        website_url  = "https://chat.openai.com",
        account_url  = "https://chat.openai.com/",
        billing_url  = "https://platform.openai.com/account/billing/overview",
        link_notes   = "Billing may be managed via Apple or Google subscriptions if purchased via mobile",
        logo_color   = "#10A37F",
        logo_path    = "/assets/logos/chatgpt.png",
        is_active    = True,
    ),
    dict(
        name         = "Claude",
        slug         = "claude",
        category     = "chat",
        website_url  = "https://claude.ai",
        account_url  = "https://claude.ai/",
        billing_url  = "https://claude.ai/settings/billing",
        link_notes   = "Login may be via Google; billing managed in-app",
        logo_color   = "#D97706",
        logo_path    = "/assets/logos/Claude.png",
        is_active    = True,
    ),
    dict(
        name         = "Cursor",
        slug         = "cursor",
        category     = "coding",
        website_url  = "https://cursor.sh",
        account_url  = "https://cursor.sh/settings",
        billing_url  = "https://cursor.sh/settings/billing",
        link_notes   = "Billing tied to Cursor account",
        logo_color   = "#1A1A1A",
        logo_path    = "/assets/logos/cursor.svg",
        is_active    = True,
    ),
    dict(
        name         = "ElevenLabs",
        slug         = "elevenlabs",
        category     = "audio",
        website_url  = "https://elevenlabs.io",
        account_url  = "https://elevenlabs.io/subscription",
        billing_url  = "https://elevenlabs.io/subscription",
        link_notes   = "Usage and billing managed in subscription page",
        logo_color   = "#F97316",
        logo_path    = "/assets/logos/elevenlabs.svg",
        is_active    = True,
    ),
    dict(
        name         = "Gemini",
        slug         = "gemini",
        category     = "chat",
        website_url  = "https://gemini.google.com",
        account_url  = "https://gemini.google.com/",
        billing_url  = "https://one.google.com/about/plans",
        link_notes   = "Subscription managed through Google One",
        logo_color   = "#4285F4",
        logo_path    = "/assets/logos/gemini.svg",
        is_active    = True,
    ),
    dict(
        name         = "GitHub Copilot",
        slug         = "github-copilot",
        category     = "coding",
        website_url  = "https://github.com/features/copilot",
        account_url  = "https://github.com/settings/copilot",
        billing_url  = "https://github.com/settings/billing",
        link_notes   = "Managed through GitHub billing settings",
        logo_color   = "#24292E",
        logo_path    = "/assets/logos/github-copilot.svg",
        is_active    = True,
    ),
    dict(
        name         = "Leonardo AI",
        slug         = "leonardo-ai",
        category     = "image",
        website_url  = "https://app.leonardo.ai",
        account_url  = "https://app.leonardo.ai/account",
        billing_url  = "https://app.leonardo.ai/account",
        link_notes   = "Credits and subscription managed in app",
        logo_color   = "#92400E",
        logo_path    = "/assets/logos/leonardo-ai.svg",
        is_active    = True,
    ),
    dict(
        name         = "Luma AI",
        slug         = "luma-ai",
        category     = "video",
        website_url  = "https://lumalabs.ai",
        account_url  = "https://lumalabs.ai/account",
        billing_url  = "https://lumalabs.ai/account",
        link_notes   = "Billing tied to account dashboard",
        logo_color   = "#0EA5E9",
        logo_path    = "/assets/logos/luma.png",
        is_active    = True,
    ),
    dict(
        name         = "MidJourney",
        slug         = "midjourney",
        category     = "image",
        website_url  = "https://midjourney.com",
        account_url  = "https://www.midjourney.com/account/",
        billing_url  = "https://www.midjourney.com/account/",
        link_notes   = "Also accessible via Discord /subscribe",
        logo_color   = "#7C3AED",
        logo_path    = "/assets/logos/midjourney.svg",
        is_active    = True,
    ),
    dict(
        name         = "Perplexity",
        slug         = "perplexity",
        category     = "chat",
        website_url  = "https://perplexity.ai",
        account_url  = "https://www.perplexity.ai/settings",
        billing_url  = "https://www.perplexity.ai/settings/billing",
        link_notes   = "Pro subscription managed via web or mobile store",
        logo_color   = "#20808D",
        logo_path    = "/assets/logos/perplexity.svg",
        is_active    = True,
    ),
    dict(
        name         = "Pika",
        slug         = "pika",
        category     = "video",
        website_url  = "https://pika.art",
        account_url  = "https://pika.art/account",
        billing_url  = "https://pika.art/account",
        link_notes   = "Video generation credits and subscription",
        logo_color   = "#6366F1",
        logo_path    = "/assets/logos/pika.svg",
        is_active    = True,
    ),
    dict(
        name         = "Replit",
        slug         = "replit",
        category     = "coding",
        website_url  = "https://replit.com",
        account_url  = "https://replit.com/account",
        billing_url  = "https://replit.com/account/billing",
        link_notes   = "Part of Replit subscription (includes Ghostwriter)",
        logo_color   = "#F55F27",
        logo_path    = "/assets/logos/replit-color.svg",
        is_active    = True,
    ),
    dict(
        name         = "Runway",
        slug         = "runway",
        category     = "video",
        website_url  = "https://runwayml.com",
        account_url  = "https://app.runwayml.com/account",
        billing_url  = "https://app.runwayml.com/account",
        link_notes   = "Credits and subscription managed in dashboard",
        logo_color   = "#000000",
        logo_path    = "/assets/logos/runway-black.svg",
        is_active    = True,
    ),
    dict(
        name         = "Stability AI",
        slug         = "stability-ai",
        category     = "image",
        website_url  = "https://dreamstudio.ai",
        account_url  = "https://dreamstudio.ai/account",
        billing_url  = "https://dreamstudio.ai/account",
        link_notes   = "Pay-as-you-go credits system",
        logo_color   = "#6D28D9",
        logo_path    = "/assets/logos/stability-color-ai.svg",
        is_active    = True,
    ),
    dict(
        name         = "Suno",
        slug         = "suno",
        category     = "audio",
        website_url  = "https://suno.com",
        account_url  = "https://suno.com/account",
        billing_url  = "https://suno.com/account",
        link_notes   = "Credits and subscription managed in account page",
        logo_color   = "#EC4899",
        logo_path    = "/assets/logos/Suno.jpeg",
        is_active    = True,
    ),
    dict(
        name         = "Udio",
        slug         = "udio",
        category     = "audio",
        website_url  = "https://udio.com",
        account_url  = "https://www.udio.com/",
        billing_url  = "https://www.udio.com/",
        link_notes   = None,
        logo_color   = "#8B5CF6",
        logo_path    = "/assets/logos/udio-color.svg",
        is_active    = True,
    ),
]
# fmt: on
